In [1]:
#IMPORT LIBARIES
# Pandas is used for reading and manipulating datasets
import pandas as pd

# Numpy helps with numerical computations
import numpy as np

#Machine Learning Algorithms
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

# Used to split dataset into training and testing data
from sklearn.model_selection import train_test_split

# Used to evaluate classification models
from sklearn.metrics import accuracy_score

# Converts text columns into numerics values
from sklearn.preprocessing import LabelEncoder

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Dataset 2.csv to Dataset 2 (1).csv

In [6]:
# Q1 Load the dataset and display the first five records.

df = pd.read_csv("Dataset 2.csv")

#Display first 5 rows
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [10]:
# Q2. Determine the number of rows and columns in the dataset.
print('rows:', len(df))
print('columns:' , len(df.columns))

rows: 750
columns: 10

In [11]:
# Q3. Display all column names.

print('column names:', df.columns)

column names: Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

In [16]:
# Q4. Identify numerical and categorical features.

le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['SubscriptionType']=le.fit_transform(df['SubscriptionType'])
df['SubscriptionRenewed']=le.fit_transform(df['SubscriptionRenewed'])
df['Age']=le.fit_transform(df['Age'])
df['UserID']=le.fit_transform(df['UserID'])

In [71]:
# Q5. # Check missing values
df.isnull().sum()

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

In [23]:
# Part B: Exploratory Data Analysis
# Q6. Calculate the average age of users.

#Average Age
print("average Age:", round(df['Age'].mean(),5))

average Age: 23.824

In [25]:
# Q7. Determine the average watch hours per week.

print("average Watch:", round(df['WatchHoursPerWeek'].mean(),10))

average Watch: 14.236

In [28]:
# Q8. Find the average monthly spending of users.

print("average monthly spending:", df['MonthlySpend'].mean())

average monthly spending: 689.9053333333334

In [31]:
# Q9. Count the number of users in each subscription category.
print(df['SubscriptionType'].value_counts())

SubscriptionType
0    342
1    279
2    129
Name: count, dtype: int64

In [32]:
# Q10 Determine the percentage of users who renewed their subscriptions.
print("percentage of users:", df['SubscriptionRenewed'].sum()/len(df)*100)

percentage of users: 46.266666666666666

In [33]:
# Part C: Data Preparation
# Q11. Convert categorical features into numerical form.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UserID               750 non-null    int64
 1   Age                  750 non-null    int64
 2   Gender               750 non-null    int64
 3   SubscriptionType     750 non-null    int64
 4   WatchHoursPerWeek    750 non-null    int64
 5   DevicesUsed          750 non-null    int64
 6   FavoriteGenre        750 non-null    object
 7   AdClicks             750 non-null    int64
 8   MonthlySpend         750 non-null    int64
 9   SubscriptionRenewed  750 non-null    int64
dtypes: int64(9), object(1)
memory usage: 58.7+ KB

In [44]:
# Q12. Define the feature set (X) and target variable (y) for subscription renewal prediction.

X = df.drop('SubscriptionRenewed', axis=1)

y = df['SubscriptionRenewed']
print(X.head())
print(y.head())

   UserID  Age  Gender  SubscriptionType  WatchHoursPerWeek  DevicesUsed  \
0       0    4       0                 0                 23            5
1       1   37       1                 0                  9            4
2       2   31       1                 0                  8            3
3       3   21       0                 1                 19            5
4       4   20       0                 1                 23            5

   FavoriteGenre  AdClicks  MonthlySpend
0              1        13           353
1              2        14           317
2              1        16           309
3              2        45           833
4              5        24           804
0    0
1    1
2    0
3    1
4    1
Name: SubscriptionRenewed, dtype: int64

In [45]:
# Q13. Split the dataset into training and testing sets.

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (600, 9)
Testing data: (150, 9)

In [65]:
# Q14 Train a Decision Tree model to predict whether a user will renew their subscription.
from sklearn.metrics import confusion_matrix
X= df.drop('SubscriptionRenewed', axis=1)
y= df['SubscriptionRenewed']
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)
dt= DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)

print('Decision tree accuracy:' , accuracy_score(y_test, y_pred))

Decision tree accuracy: 0.5666666666666667

In [63]:
# Q15 Evaluate the model using accuracy.
accuracy = accuracy_score(y_test, y_pred)
print("Decision Tree Accuracy:", accuracy)

Decision Tree Accuracy: 0.5666666666666667

In [64]:
# Q16. Generate and interpret the confusion matrix.
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[50 32]
 [33 35]]

In [67]:
#Q17. Train a KNN classifier with K = 5.

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("KNN Accuracy:", accuracy)
#

KNN Accuracy: 0.5666666666666667

In [68]:
#Q18. Compare the accuracy of KNN with the Decision Tree model.
print("Decision Tree Accuracy:", accuracy)

Decision Tree Accuracy: 0.5666666666666667

In [69]:
#Q19. Train a Linear Regression model to predict monthly spending.
from sklearn.linear_model import LinearRegression
X = df.drop(['UserID','MonthlySpend'], axis=1)
y = df['MonthlySpend']
print(X.shape)
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
lr = LinearRegression()
lr.fit(X_train, y_train)

spending = lr.predict(X_test)
print("Predicted Spending:", spending)

(750, 8)
(750,)
Predicted Spending: [ 840.62490183  373.27988237  800.32286357  327.10940057  357.73088454
 1317.86932915  818.11663206  852.14385663 1289.68997525 1314.81235149
  853.90113674 1264.18557251  884.01331733 1302.07824724  290.33305364
  793.08203399  792.29481149  356.40051444  880.4999532   824.77533461
  867.83601019 1281.49215736  329.78537838  402.39559625 1361.9680061
 1287.6231789  1344.83111954  848.36219987  809.82373111  300.71150582
  851.3527454   863.31616414  772.00990938  337.47912172 1310.97275443
 1288.67710193  830.70799714  311.36516052  868.22539785  806.63513289
  291.52633938  380.6729002   788.11597102  879.24592642 1297.55209415
  870.03182878  857.32826903  308.24721379  362.85908399  324.82364517
  846.58660883  349.86072125  317.14748409 1340.70550289  789.26292231
  766.3023544   850.18117472  863.89459804 1310.5279959   289.99564484
  796.68013986 1362.89443562  360.12387124  289.45168717  778.84442404
  353.80289407  315.08863827 1366.73672732  293.96897445  356.93869567
  792.80666758  789.81096403  859.1831598   350.13844097  324.96376187
  842.61490027  284.26390807  383.60410462  365.58620663  351.37039372
  845.07941042  824.84400586  771.71531935  299.29008421  848.55533687
  819.17928821  319.75541208  360.38444002 1329.10173836 1268.02377953
  901.16749353  846.42419078  351.19212902  835.86177999  350.62565604
  824.14762594  321.31422012  329.67184746  282.1017514   359.35590804
  762.60545845 1343.3563646   317.62648763 1298.12810462  368.93440798
  327.22132882  320.26635112 1326.49707282  349.15119975 1320.21475959
  351.35122003 1372.94673198  371.33593707  368.85241721  358.91220511
  356.40037918 1307.63729606  794.02495644  450.66170684  884.36721607
  850.0062724   401.03110585  282.82749253  319.47487032  360.29262441
  845.27682417 1313.42778477  908.01523169  358.46824586  366.17963079
  295.05481408  349.95323419  347.58178092  817.33943041  884.48458643
  366.87537778  776.61711122  382.62722832  305.80430467  833.56256701
  829.03186454 1361.18535471  826.15988031  323.78120063  341.76765041
  771.14920135  294.24123012  845.76654889 1281.34828355  372.39848694]

In [70]:
# Q20. Predict the monthly spending for a new user and interpret the result.

user = pd.DataFrame({
    'Age':[30],
    'Gender':[1],
    'SubscriptionType':[2],
    'WatchHoursPerWeek':[15],
    'DevicesUsed':[3],
    'FavoriteGenre':[1],
    'AdClicks':[8],
    'SubscriptionRenewed':[1]
})
prediction = lr.predict(user)

print("Predicted Monthly Spending:", prediction[0])

Predicted Monthly Spending: 1314.611113392784